# configs/exp6_msca_afpn_softnms.yaml

# MSCA + AFPN + Soft-NMS


name: exp6_msca_afpn_softnms
model_yaml: src/models/masw-yolo-afpn.yaml
weights: yolov8n.pt

soft_nms: true
soft_nms_method: gaussian    
soft_nms_sigma: 0.5
soft_nms_score_thres: 0.001
